import json
import re

search_sites = [
    ("youtube", "https://www.youtube.com/results?search_query="),
    ("amazon", "https://www.amazon.com/s?k="),
    ("ebay", "https://www.ebay.com/sch/i.html?_nkw="),
    ("reddit", "https://www.reddit.com/search/?q="),
    ("wikipedia", "https://en.wikipedia.org/wiki/Special:Search?search="),
    ("github", "https://github.com/search?q="),
    ("stackoverflow", "https://stackoverflow.com/search?q="),
    ("twitter", "https://twitter.com/search?q="),
    ("x", "https://twitter.com/search?q="),
    ("facebook", "https://www.facebook.com/search/top/?q="),
    ("linkedin", "https://www.linkedin.com/search/results/all/?keywords="),
    ("pinterest", "https://www.pinterest.com/search/pins/?q="),
    ("netflix", "https://www.netflix.com/search?q="),
    ("hulu", "https://www.hulu.com/search?q="),
    ("disney plus", "https://www.disneyplus.com/search?q="),
    ("prime video", "https://www.amazon.com/s?k="),
    ("twitch", "https://www.twitch.tv/search?term="),
    ("spotify", "https://open.spotify.com/search/"),
    ("soundcloud", "https://soundcloud.com/search?q="),
    ("imdb", "https://www.imdb.com/find?q="),
    ("bing", "https://www.bing.com/search?q="),
    ("yahoo", "https://search.yahoo.com/search?p="),
    ("duckduckgo", "https://duckduckgo.com/?q="),
    ("baidu", "https://www.baidu.com/s?wd="),
    ("yandex", "https://yandex.com/search/?text="),
    ("chatgpt", "https://chatgpt.com/?q="),
    ("claude", "https://claude.ai/new?q="),
    ("perplexity", "https://www.perplexity.ai/search?q="),
    ("phind", "https://www.phind.com/search?q="),
    ("you", "https://you.com/search?q="),
    ("quora", "https://www.quora.com/search?q="),
    ("medium", "https://medium.com/search?q="),
    ("cnn", "https://edition.cnn.com/search?q="),
    ("bbc", "https://www.bbc.co.uk/search?q="),
    ("fox news", "https://www.foxnews.com/search-results/search?q="),
    ("nytimes", "https://www.nytimes.com/search?query="),
    ("wsj", "https://www.wsj.com/search?keyword="),
    ("the guardian", "https://www.theguardian.com/info/developer-blog/search?q="),
    ("forbes", "https://www.forbes.com/search/?q="),
    ("bloomberg", "https://www.bloomberg.com/search?query="),
    ("reuters", "https://www.reuters.com/search/news?blob="),
    ("al jazeera", "https://www.aljazeera.com/search/"),
    ("walmart", "https://www.walmart.com/search?q="),
    ("target", "https://www.target.com/s?searchTerm="),
    ("best buy", "https://www.bestbuy.com/site/searchpage.jsp?st="),
    ("home depot", "https://www.homedepot.com/s/"),
    ("lowes", "https://www.lowes.com/search?searchTerm="),
    ("costco", "https://www.costco.com/CatalogSearch?dept=All&keyword="),
    ("macys", "https://www.macys.com/shop/featured/"),
    ("nordstrom", "https://www.nordstrom.com/sr?origin=keywordsearch&keyword="),
    ("ikea", "https://www.ikea.com/us/en/search/?q="),
    ("wayfair", "https://www.wayfair.com/keyword.php?keyword="),
    ("etsy", "https://www.etsy.com/search?q="),
    ("aliexpress", "https://www.aliexpress.com/wholesale?SearchText="),
    ("alibaba", "https://www.alibaba.com/trade/search?SearchText="),
    ("zillow", "https://www.zillow.com/homes/"),
    ("trulia", "https://www.trulia.com/"),
    ("realtor", "https://www.realtor.com/realestateandhomes-search/"),
    ("craigslist", "https://craigslist.org/search/sss?query="),
    ("tripadvisor", "https://www.tripadvisor.com/Search?q="),
    ("expedia", "https://www.expedia.com/"),
    ("kayak", "https://www.kayak.com/"),
    ("booking", "https://www.booking.com/searchresults.html?ss="),
    ("airbnb", "https://www.airbnb.com/s/"),
    ("uber", "https://www.uber.com/"),
    ("lyft", "https://www.lyft.com/"),
    ("yelp", "https://www.yelp.com/search?find_desc="),
    ("doordash", "https://www.doordash.com/search/store/"),
    ("ubereats", "https://www.ubereats.com/search?q="),
    ("grubhub", "https://www.grubhub.com/search?q="),
    ("postmates", "https://postmates.com/search?q="),
    ("instacart", "https://www.instacart.com/store/s?k="),
    ("coursera", "https://www.coursera.org/search?query="),
    ("udemy", "https://www.udemy.com/courses/search/?q="),
    ("edx", "https://www.edx.org/search?q="),
    ("khan academy", "https://www.khanacademy.org/search?page_search_query="),
    ("skillshare", "https://www.skillshare.com/search?query="),
    ("masterclass", "https://www.masterclass.com/search?query="),
    ("codecademy", "https://www.codecademy.com/search?query="),
    ("datacamp", "https://www.datacamp.com/search?q="),
    ("leetcode", "https://leetcode.com/problemset/all/?search="),
    ("hackerrank", "https://www.hackerrank.com/"),
    ("codewars", "https://www.codewars.com/users/search?q="),
    ("npm", "https://www.npmjs.com/search?q="),
    ("pypi", "https://pypi.org/search/?q="),
    ("docker hub", "https://hub.docker.com/search?q="),
    ("crates", "https://crates.io/search?q="),
    ("nuget", "https://www.nuget.org/packages?q="),
    ("maven", "https://mvnrepository.com/search?q="),
    ("packagist", "https://packagist.org/search/?q="),
    ("rubygems", "https://rubygems.org/search?query="),
    ("godoc", "https://pkg.go.dev/search?q="),
    ("mdn", "https://developer.mozilla.org/en-US/search?q="),
    ("w3schools", "https://www.w3schools.com/"),
    ("geeksforgeeks", "https://www.geeksforgeeks.org/"),
    ("tutorialspoint", "https://www.tutorialspoint.com/search.htm?q="),
    ("javatpoint", "https://www.javatpoint.com/"),
    ("fandom", "https://community.fandom.com/wiki/Special:Search?query="),
    ("ign", "https://www.ign.com/search?q="),
    ("gamespot", "https://www.gamespot.com/search/?q="),
    ("polygon", "https://www.polygon.com/search?q="),
    ("kotaku", "https://kotaku.com/search?q="),
    ("pcgamer", "https://www.pcgamer.com/search/?searchTerm="),
    ("rockpapershotgun", "https://www.rockpapershotgun.com/search?q="),
    ("eurogamer", "https://www.eurogamer.net/search?q="),
    ("destructoid", "https://www.destructoid.com/?s="),
    ("giantbomb", "https://www.giantbomb.com/search/?q="),
    ("gamefaqs", "https://gamefaqs.gamespot.com/search?game="),
    ("metacritic", "https://www.metacritic.com/search/all/"),
    ("rotten tomatoes", "https://www.rottentomatoes.com/search?search="),
    ("vimeo", "https://vimeo.com/search?q="),
    ("dailymotion", "https://www.dailymotion.com/search/"),
    ("tiktok", "https://www.tiktok.com/search?q="),
    ("snapchat", "https://www.snapchat.com/"),
    ("instagram", "https://www.instagram.com/"),
    ("whatsapp", "https://web.whatsapp.com/"),
    ("telegram", "https://web.telegram.org/"),
    ("discord", "https://discord.com/"),
    ("slack", "https://slack.com/"),
    ("teams", "https://teams.microsoft.com/"),
    ("zoom", "https://zoom.us/"),
    ("skype", "https://www.skype.com/en/"),
    ("webex", "https://www.webex.com/"),
    ("meet", "https://meet.google.com/"),
    ("gmail", "https://mail.google.com/mail/u/0/#search/"),
    ("outlook", "https://outlook.live.com/mail/0/"),
    ("yahoo mail", "https://mail.yahoo.com/"),
    ("protonmail", "https://protonmail.com/"),
    ("icloud", "https://www.icloud.com/"),
    ("drive", "https://drive.google.com/drive/search?q="),
    ("dropbox", "https://www.dropbox.com/"),
    ("onedrive", "https://onedrive.live.com/"),
    ("box", "https://www.box.com/"),
    ("mega", "https://mega.io/"),
    ("mediafire", "https://www.mediafire.com/"),
    ("civitai", "https://civitai.com/search/models?sortBy=models_v9&query="),
    ("huggingface", "https://huggingface.co/search/full-text?q="),
    ("poe", "https://poe.com/"),
    ("replit", "https://replit.com/search?q=")
]

code = "\n# AUTO-GENERATED 200+ UNIVERSAL MACROS\n"
code += "more_universal = [\n"
for name, url in search_sites:
    if url.endswith("=") or url.endswith("?q=") or url.endswith("text=") or url.endswith("term=") or url.endswith("search="):
        code += f"""    {{"intent": "search {{query}} on {name}", "actions": [
        {{"type": "key", "key": "win+r"}},
        {{"type": "sleep", "ms": 800}},
        {{"type": "type", "text": "brave {url}{{query}}"}},
        {{"type": "sleep", "ms": 800}},
        {{"type": "key", "key": "enter"}}
    ]}},\n"""
    else:
        # If it doesn't have a direct search query URL, just navigate there
        code += f"""    {{"intent": "open {name}", "actions": [
        {{"type": "key", "key": "win+r"}},
        {{"type": "sleep", "ms": 800}},
        {{"type": "type", "text": "brave {url}"}},
        {{"type": "sleep", "ms": 800}},
        {{"type": "key", "key": "enter"}}
    ]}},\n"""

code = code.rstrip(",\n") + "\n]\n"
code += "skills.extend(more_universal)\n"

# Append to train_skills.py before the writing block
with open("train_skills.py", "r") as f:
    content = f.read()

# Insert before '# Write to disk'
content = content.replace("# Write to disk", code + "\n# Write to disk")

with open("train_skills.py", "w") as f:
    f.write(content)

print(f"Added {len(search_sites)} universal search macros to train_skills.py!")
